import {
  AntDesign,
  Entypo,
  EvilIcons,
  Feather,
  FontAwesome,
  FontAwesome5,
  FontAwesome6,
  Fontisto,
  Foundation,
  Ionicons,
  MaterialIcons,
  MaterialCommunityIcons,
  Octicons,
  SimpleLineIcons,
  Zocial,
} from "@expo/vector-icons"

export const IconFamilies: any = {
  AntDesign,
  Entypo,
  EvilIcons,
  Feather,
  FontAwesome,
  FontAwesome5,
  FontAwesome6,
  Fontisto,
  Foundation,
  Ionicons,
  MaterialIcons,
  MaterialCommunityIcons,
  Octicons,
  SimpleLineIcons,
  Zocial,
}

export enum ICON_FAMILY_NAME {
  AntDesign = "AntDesign",
  Entypo = "Entypo",
  EvilIcons = "EvilIcons",
  Feather = "Feather",
  FontAwesome = "FontAwesome",
  FontAwesome5 = "FontAwesome5",
  FontAwesome6 = "FontAwesome6",
  Fontisto = "Fontisto",
  Foundation = "Foundation",
  Ionicons = "Ionicons",
  MaterialIcons = "MaterialIcons",
  MaterialCommunityIcons = "MaterialCommunityIcons",
  Octicons = "Octicons",
  SimpleLineIcons = "SimpleLineIcons",
  Zocial = "SimpleLineIconZocials",
}